OpenWindow(#wnd,0,0,1280,720,#myNameVer,#PB_Window_SizeGadget|#PB_Window_SizeGadget|#PB_Window_SystemMenu|#PB_Window_MinimizeGadget|#PB_Window_ScreenCentered)
WindowBounds(#wnd,1280,720,#PB_Ignore,#PB_Ignore)
  
CreateMenu(#menu,WindowID(#wnd))

MenuTitle("File")
MenuItem(#openPlaylist,"Open Playlist...")
MenuItem(#savePlaylist,"Save Playlist...")
MenuBar()
MenuItem(#addDirectory,"Add Diectory...")
MenuItem(#addFile,"Add File(s)...")

MenuTitle("Playback")
MenuItem(#playbackCursorFollowsPlayback,"Cursor follows playback")
MenuItem(#playbackPlaybackFollowsCursor,"Playback follows cursor")
OpenSubMenu("Order")
MenuItem(#playbackOrderDefault,"Default")
MenuItem(#playbackOrderShuffleTracks,"Shuffle (tracks)")
MenuItem(#playbackOrderShuffleAlbums,"Shuffle (albums)")
CloseSubMenu()
MenuBar()
MenuItem(#playbackStopAtQueueEnd,"Stop at queue end")

MenuTitle("Last.fm")
MenuItem(#lastfmState,"")
MenuBar()
MenuItem(#lastfmUser,"")
DisableMenuItem(#menu,#lastfmUser,#True)

CreatePopupMenu(#playlistMenu)
MenuItem(#playlistQueue,"Queue")
MenuItem(#playlistPlay,"Play" + Chr(9) + "⏎")
MenuItem(#playlistReloadTags,"Reload tags" + Chr(9) + "R")
MenuItem(#playlistRemove,"Remove from playlist" + Chr(9) + "⌫")

ListIconGadget(#playlist,0,0,WindowWidth(#wnd)-500,WindowHeight(#wnd),"",35)
AddGadgetColumn(#playlist,#file,"File",200)
AddGadgetColumn(#playlist,#track,"#",25)
AddGadgetColumn(#playlist,#artist,"Artist",200)
AddGadgetColumn(#playlist,#title,"Title",200)
AddGadgetColumn(#playlist,#duration,"Duration",65)
AddGadgetColumn(#playlist,#album,"Album",150)
AddGadgetColumn(#playlist,#details,"Details",80)

ListIconGadgetHideColumn(#playlist,#file,#True)
SetListIconColumnJustification(#playlist,#status,#justifyCenter)
SetListIconColumnJustification(#playlist,#track,#justifyRight)
SetListIconColumnJustification(#playlist,#duration,#justifyCenter)
SetListIconColumnJustification(#playlist,#details,#justifyRight)
;CocoaMessage(0,GadgetID(#playlist),"setGridStyleMask:",1)
;CocoaMessage(0, GadgetID(#playlist), "setUsesAlternatingRowBackgroundColors:", #YES)
;CocoaMessage(0, GadgetID(#playlist), "setUsesAutomaticRowHeights:", #YES)
CocoaMessage(0,GadgetID(#playlist),"setAllowsTypeSelect:",#NO)

LoadFont(1,"Menlo",24,#PB_Font_Bold)
CreateImage(#defaultAlbumArt,500,500)
StartDrawing(ImageOutput(#defaultAlbumArt))
DrawingFont(FontID(1))
Box(0,0,500,500,0)
DrawText(500/2-TextWidth("[no album art]")/2,500/2-TextHeight("[no album art]")/2,"[no album art]",$CCCCCC,0)
StopDrawing()
FreeFont(1)
ImageGadget(#albumArt,WindowWidth(#wnd)-500,0,500,500,ImageID(#defaultAlbumArt))

TextGadget(#nowPlaying,WindowWidth(#wnd)-500,500,500,59,"",#PB_Text_Center)
TextGadget(#nowPlayingDuration,WindowWidth(#wnd)-500,559,500,16,"[standby]",#PB_Text_Center)
ProgressBarGadget(#nowPlayingProgress,WindowWidth(#wnd)-495,575,490,20,0,100)

ButtonGadget(#toolbarPreviousAlbum,WindowWidth(#wnd)-495,595,50,25,#previousAlbumSymbol)
ButtonGadget(#toolbarPrevious,WindowWidth(#wnd)-445,595,50,25,#previousSymbol)
ButtonGadget(#toolbarPlayPause,WindowWidth(#wnd)-395,595,50,25,#playSymbol)
ButtonGadget(#toolbarNext,WindowWidth(#wnd)-345,595,50,25,#nextSymbol)
ButtonGadget(#toolbarNextAlbum,WindowWidth(#wnd)-295,595,50,25,#nextAlbumSymbol)
ButtonGadget(#toolbarStop,WindowWidth(#wnd)-245,595,50,25,#stopSymbol)
ButtonGadget(#toolbarLyricsReloadWeb,WindowWidth(#wnd)-55,595,50,25,#refreshSymbol)

GadgetToolTip(#toolbarPreviousAlbum,"Previous Album")
GadgetToolTip(#toolbarPrevious,"Previous Track")
GadgetToolTip(#toolbarPlayPause,"Play/Pause")
GadgetToolTip(#toolbarNext,"Next Track")
GadgetToolTip(#toolbarNextAlbum,"Next Album")
GadgetToolTip(#toolbarStop,"Stop")
GadgetToolTip(#toolbarLyricsReloadWeb,"Reload lyrics from Genius")

EditorGadget(#lyrics,WindowWidth(#wnd)-500,620,500,WindowHeight(#wnd)-620,#PB_Editor_ReadOnly|#PB_Editor_WordWrap)
If Not lyricsAvailable
  SetGadgetText(#lyrics,"[lyrics disabled]")
  HideGadget(#lyrics,#True)
EndIf
HideGadget(#toolbarLyricsReloadWeb,#True)

Macro prefs()
  OpenWindow(#wndPrefs,0,0,400,300,#myName + " Preferences",#PB_Window_ScreenCentered|#PB_Window_SystemMenu|#PB_Window_Tool,WindowID(#wnd))
  ;StickyWindow(#wndPrefs,#True)
  PanelGadget(#prefsPanel,0,0,400,300)
  AddGadgetItem(#prefsPanel,-1,"Web")
  CheckBoxGadget(#prefsWebEnable,10,5,240,20,"Enable web server")
  HyperLinkGadget(#prefsWebLink,250,9,160,20,"",$00aa00,#PB_HyperLink_Underline)
  TextGadget(#prefsWebPortLabel,10,35,250,20,"Web server port (1025-65534):")
  SpinGadget(#prefsWebPort,10,55,80,20,1025,65534,#PB_Spin_Numeric)
  CocoaMessage(0,GadgetID(#prefsWebPort),"setFocusRingType:",1)
  TextGadget(#prefsWebApiKeyLabel,10,85,350,20,"API key (used for authorization, leave blank to generate):")
  StringGadget(#prefsWebApiKey,10,105,350,20,"")
  CocoaMessage(0,GadgetID(#prefsWebApiKey),"setFocusRingType:",1)
  SetGadgetColor(#prefsWebLink,#PB_Gadget_FrontColor,$458c1e)
  SetGadgetText(#prefsWebPort,Str(settings\web\web_server_port))
  SetGadgetState(#prefsWebPort,settings\web\web_server_port)
  SetGadgetText(#prefsWebApiKey,settings\web\api_key)
  If settings\web\use_web_server
    SetGadgetState(#prefsWebEnable,#PB_Checkbox_Checked)
    DisableGadget(#prefsWebPort,#True)
  EndIf
  If IsThread(webThread)
    HideGadget(#prefsWebLink,#False)
    SetGadgetText(#prefsWebLink,"running on port " + Str(settings\web\web_server_port))
  Else
    HideGadget(#prefsWebLink,#True)
  EndIf
EndMacro