import Foundation
@testable import iCanHazMusic

struct FixtureError: Error, CustomStringConvertible {
    let description: String
}

/// Files generated by `tests/prepare-fixtures.sh` into `tests/fixtures/generated` (git-ignored).
enum Fixtures {
    static let directory = URL(fileURLWithPath: #filePath)
        .deletingLastPathComponent()      // Support
        .deletingLastPathComponent()      // tests
        .appendingPathComponent("fixtures/generated", isDirectory: true)

    /// The fixture at `relative` (e.g. `formats/t.flac`). Throws with a hint if the fixtures aren't generated.
    static func url(_ relative: String) throws -> URL {
        let url = directory.appendingPathComponent(relative)
        guard FileManager.default.fileExists(atPath: url.path) else {
            throw FixtureError(description: "missing fixture '\(relative)': run tests/prepare-fixtures.sh (needs ffmpeg)")
        }
        return url
    }

    static func data(_ relative: String) throws -> Data {
        try Data(contentsOf: url(relative))
    }

    // What every fully tagged fixture of `prepare-fixtures.sh` carries.
    static let title = "TTitle"
    static let artist = "TArtist"
    static let album = "TAlbum"
    static let year = "2020"
    static let trackNumber = 3
    /// Length of every generated audio file, in seconds.
    static let duration = 2.0
}

/// A scratch directory under one per-run root. Directories are not removed individually (a test may well
/// outlive its last use of the object); the whole root goes away when the test process exits.
final class TempDir {
    private static let root: URL = {
        let root = FileManager.default.temporaryDirectory
            .appendingPathComponent("ichm-tests-\(ProcessInfo.processInfo.processIdentifier)", isDirectory: true)
        try? FileManager.default.removeItem(at: root)
        try? FileManager.default.createDirectory(at: root, withIntermediateDirectories: true)
        atexit { try? FileManager.default.removeItem(at: TempDir.root) }
        return root
    }()

    let url: URL

    init() throws {
        url = Self.root.appendingPathComponent(UUID().uuidString, isDirectory: true)
        try FileManager.default.createDirectory(at: url, withIntermediateDirectories: true)
    }

    func path(_ relative: String) -> URL {
        url.appendingPathComponent(relative)
    }

    @discardableResult
    func mkdir(_ relative: String) throws -> URL {
        let dir = path(relative)
        try FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
        return dir
    }

    /// Writes a file (creating its directories).
    @discardableResult
    func write(_ relative: String, _ data: Data = Data()) throws -> URL {
        let file = path(relative)
        try FileManager.default.createDirectory(at: file.deletingLastPathComponent(), withIntermediateDirectories: true)
        try data.write(to: file)
        return file
    }

    /// Copies a generated fixture into the directory.
    @discardableResult
    func copy(_ fixture: String, to relative: String) throws -> URL {
        try write(relative, Fixtures.data(fixture))
    }

    /// Paths of `urls` relative to the directory, whichever way the temp dir is spelled (`/var` vs `/private/var`).
    func relative(_ urls: [URL]) -> [String] {
        let prefixes = [url.path, url.standardizedFileURL.path, url.resolvingSymlinksInPath().path]
            .sorted { $0.count > $1.count }
        return urls.map { u in
            let p = u.path
            for prefix in prefixes where p.hasPrefix(prefix + "/") { return String(p.dropFirst(prefix.count + 1)) }
            return p
        }
    }
}

/// Polls `condition` (on the main actor) until it holds or `timeout` passes. Returns whether it held.
@MainActor
func waitUntil(timeout: TimeInterval = 5, _ condition: @MainActor () -> Bool) async -> Bool {
    let deadline = Date().addingTimeInterval(timeout)
    while Date() < deadline {
        if condition() { return true }
        try? await Task.sleep(for: .milliseconds(10))
    }
    return condition()
}

// MARK: - Byte helpers for hand-built files

extension Data {
    static func be32(_ value: Int) -> Data {
        Data([UInt8(value >> 24 & 255), UInt8(value >> 16 & 255), UInt8(value >> 8 & 255), UInt8(value & 255)])
    }

    static func le32(_ value: Int) -> Data {
        Data([UInt8(value & 255), UInt8(value >> 8 & 255), UInt8(value >> 16 & 255), UInt8(value >> 24 & 255)])
    }

    /// `text` as ASCII/UTF-8 bytes, padded with NULs / cut to exactly `count` bytes.
    static func fixed(_ text: String, _ count: Int) -> Data {
        var d = Data(text.utf8.prefix(count))
        d.append(Data(repeating: 0, count: count - d.count))
        return d
    }

    static func ascii(_ text: String) -> Data { Data(text.utf8) }
}

extension Data {
    // Concrete overloads: `+` chains of `.ascii(...)` / `.be32(...)` are too much for the generic
    // RangeReplaceableCollection operators (the type checker gives up).
    static func + (lhs: Data, rhs: Data) -> Data {
        var d = lhs
        d.append(rhs)
        return d
    }

    static func += (lhs: inout Data, rhs: Data) {
        lhs.append(rhs)
    }
}
